export const BASE64_TOOL_STRINGS = {
  TITLE: 'Base64 Workshop',
  DESCRIPTION: 'Encode or decode plain text, and Base64 entire files in either direction.',
  TEXT_MODE: 'Text mode',
  FILE_MODE: 'File mode',
  ENCODE: 'Text → Base64',
  DECODE: 'Base64 → Text',
  ENCODE_TITLE: 'Convert plain text into Base64',
  DECODE_TITLE: 'Convert Base64 back into plain text',
  CLEAR_TITLE: 'Clear the input',
  PLAIN_TEXT: 'Plain text',
  BASE64_STRING: 'Base64 string',
  PLACEHOLDER_ENCODE: 'Type or paste any text — even with emojis or unicode…',
  PLACEHOLDER_DECODE: 'Paste a Base64 string here…',
  BASE64_OUTPUT: 'Base64 output',
  DECODED_TEXT: 'Decoded text',
  ERROR_DECODE: "That doesn't look like valid Base64. Check for stray characters or missing padding.",
  ERROR_ENCODE: "Couldn't encode this — please try again with simpler input.",
  DROP_FILE_LABEL: "Drop any file here, or click to choose — we'll Base64-encode the bytes for you",
  BASE64_OF: 'Base64 of',
  SAVE_BACK_AS_FILE: 'Save back as file',
  SAVE_BACK_TITLE: 'Decode the Base64 back into a downloadable file',
  DOWNLOAD_PREFIX: 'decoded_',
  DEFAULT_DOWNLOAD_NAME: 'decoded_file',
};
