export const URL_TOOL_STRINGS = {
  TITLE: 'URL Encoder',
  DESCRIPTION: 'Percent-encode/decode URLs, and inspect query parameters at a glance.',
  ENCODE: 'Encode',
  DECODE: 'Decode',
  ENCODE_TITLE: 'Convert plain text to a URL-safe string',
  DECODE_TITLE: 'Decode a URL-encoded string back to plain text',
  MODE_COMPONENT: 'Mode: component (encodeURIComponent)',
  MODE_FULL: 'Mode: full URL (encodeURI)',
  MODE_TITLE: 'Component mode escapes everything (use this for query values). Full-URL mode keeps :// ? & intact.',
  LOAD_SAMPLE: 'Load sample',
  LOAD_SAMPLE_TITLE: 'Load a sample URL',
  PLACEHOLDER_INPUT: 'Paste a URL or a URL-encoded string here…',
  DECODE_FAILED: 'Decode failed',
  QUERY_PARAMS_DETECTED: 'Query parameters detected',
  PARAMETER: 'Parameter',
  VALUE: 'Value',
  ERROR_INVALID_URL: "Hmm, that doesn't look like a valid URL or encoded string.",
  SAMPLE_URL: 'https://example.com/api/search?q=hello world&filter=type:json&tag=a&tag=b',
};
