import type { ToolDefinition } from '@/types'

export const TOOLS: ToolDefinition[] = [
  // Formatters
  {
    id: 'json-formatter',
    name: 'JSON Studio',
    description: 'Pretty-print, validate, minify and even auto-repair broken JSON.',
    category: 'Formatters',
    path: '/formatters/json',
    icon: 'Braces',
    keywords: ['json', 'format', 'pretty', 'validate', 'repair', 'minify', 'lint', 'beautify'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Studio',
    description: 'Format and sanity-check XML documents with proper indentation.',
    category: 'Formatters',
    path: '/formatters/xml',
    icon: 'Code2',
    keywords: ['xml', 'format', 'pretty', 'validate', 'beautify'],
  },
  {
    id: 'yaml-formatter',
    name: 'YAML Studio',
    description: 'Tidy up YAML files and catch syntax errors before they bite.',
    category: 'Formatters',
    path: '/formatters/yaml',
    icon: 'AlignLeft',
    keywords: ['yaml', 'yml', 'format', 'validate', 'beautify'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Studio',
    description: 'Pretty-print SQL queries — pick your dialect (MySQL, Postgres, Oracle, T-SQL, SQLite).',
    category: 'Formatters',
    path: '/formatters/sql',
    icon: 'Database',
    keywords: ['sql', 'format', 'pretty', 'query', 'mysql', 'postgres', 'oracle', 'sqlite'],
  },
  // Viewers
  {
    id: 'mermaid-viewer',
    name: 'Mermaid Diagrams',
    description: 'Author Mermaid syntax and watch flowcharts, sequences and gantts render live.',
    category: 'Viewers',
    path: '/viewers/mermaid',
    icon: 'GitBranch',
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'gantt', 'uml', 'visualize'],
  },
  {
    id: 'diff-viewer',
    name: 'Text & JSON Diff',
    description: 'Compare two snippets side-by-side or inline, with character / word / line precision.',
    category: 'Viewers',
    path: '/viewers/diff',
    icon: 'SplitSquareHorizontal',
    keywords: ['diff', 'compare', 'difference', 'text', 'json', 'side by side'],
  },
  // Encoders
  {
    id: 'base64',
    name: 'Base64 Workshop',
    description: 'Encode or decode plain text, and Base64 entire files in either direction.',
    category: 'Encoders',
    path: '/encoders/base64',
    icon: 'Binary',
    keywords: ['base64', 'encode', 'decode', 'file', 'binary'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    description: 'Percent-encode/decode URLs and inspect query parameters at a glance.',
    category: 'Encoders',
    path: '/encoders/url',
    icon: 'Link',
    keywords: ['url', 'uri', 'encode', 'decode', 'percent', 'query', 'params'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Inspector',
    description: 'Decode any JSON Web Token, peek at claims, and check expiry — no key needed.',
    category: 'Encoders',
    path: '/encoders/jwt',
    icon: 'KeyRound',
    keywords: ['jwt', 'token', 'decode', 'verify', 'header', 'payload', 'claims', 'auth', 'bearer'],
    isCrypto: true,
  },
  {
    id: 'case-converter',
    name: 'Case Switcher',
    description: 'Flip text between camelCase, snake_case, PascalCase, kebab-case and more.',
    category: 'Encoders',
    path: '/encoders/case',
    icon: 'CaseSensitive',
    keywords: ['case', 'camel', 'snake', 'pascal', 'kebab', 'upper', 'lower', 'naming', 'rename'],
  },
  // Crypto
  {
    id: 'aes',
    name: 'AES Cipher',
    description: 'Encrypt or decrypt with AES — choose CBC, GCM or CTR mode and 128/192/256-bit keys.',
    category: 'Crypto',
    path: '/crypto/aes',
    icon: 'Lock',
    keywords: ['aes', 'encrypt', 'decrypt', 'cbc', 'gcm', 'ctr', 'symmetric', 'cipher'],
    isCrypto: true,
  },
  {
    id: 'jasypt',
    name: 'Jasypt for Spring',
    description: 'Drop-in compatible with `jasypt-spring-boot` — encrypt and decrypt ENC(…) values.',
    category: 'Crypto',
    path: '/crypto/jasypt',
    icon: 'ShieldCheck',
    keywords: ['jasypt', 'pbe', 'spring', 'spring boot', 'encrypt', 'decrypt', 'enc', 'config', 'properties'],
    isCrypto: true,
  },
  {
    id: 'rsa',
    name: 'RSA Toolbox',
    description: 'Generate key pairs, encrypt/decrypt with PKCS#1 or OAEP, and sign or verify messages.',
    category: 'Crypto',
    path: '/crypto/rsa',
    icon: 'Fingerprint',
    keywords: ['rsa', 'asymmetric', 'keygen', 'encrypt', 'decrypt', 'sign', 'verify', 'pem', 'pkcs', 'oaep'],
    isCrypto: true,
  },
  {
    id: 'hash',
    name: 'Hash Lab',
    description: 'Compute MD5, SHA-1/224/256/384/512, bcrypt and HMAC — all in one place.',
    category: 'Crypto',
    path: '/crypto/hash',
    icon: 'Hash',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'bcrypt', 'hmac', 'digest', 'checksum'],
    isCrypto: true,
  },
  // Generators
  {
    id: 'uuid',
    name: 'ID Generator',
    description: 'Mint UUID v1 / v4 and ULID identifiers — single or in bulk.',
    category: 'Generators',
    path: '/generators/uuid',
    icon: 'Dices',
    keywords: ['uuid', 'guid', 'ulid', 'unique', 'id', 'generate', 'identifier'],
  },
  {
    id: 'lorem',
    name: 'Mock Data',
    description: 'Generate Lorem Ipsum or realistic fake records — names, emails, addresses, finance.',
    category: 'Generators',
    path: '/generators/lorem',
    icon: 'FileText',
    keywords: ['lorem', 'ipsum', 'fake', 'mock', 'data', 'name', 'email', 'address', 'seed', 'placeholder'],
  },
  {
    id: 'qr-code',
    name: 'QR Code',
    description: 'Build QR codes from any text or URL, or decode an existing QR image.',
    category: 'Generators',
    path: '/generators/qr',
    icon: 'QrCode',
    keywords: ['qr', 'barcode', 'generate', 'decode', 'scan', 'wifi', 'vcard'],
  },
  {
    id: 'color',
    name: 'Color Studio',
    description: 'Pick a color and convert between HEX, RGB, HSL, HWB, CMYK plus a shade ramp.',
    category: 'Generators',
    path: '/generators/color',
    icon: 'Palette',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'hwb', 'cmyk', 'picker', 'convert', 'palette', 'shades'],
  },
  {
    id: 'cron',
    name: 'Cron Builder',
    description: 'Write cron expressions, get a plain-English explanation and the next 5 fire times.',
    category: 'Generators',
    path: '/generators/cron',
    icon: 'Clock',
    keywords: ['cron', 'schedule', 'expression', 'quartz', 'timer', 'k8s', 'jobs'],
  },
  // Converters
  {
    id: 'timestamp',
    name: 'Time Machine',
    description: 'Hop between Unix epoch, ISO 8601, and any timezone with relative-time hints.',
    category: 'Converters',
    path: '/converters/timestamp',
    icon: 'CalendarClock',
    keywords: ['timestamp', 'epoch', 'unix', 'date', 'time', 'iso', 'utc', 'timezone', 'tz'],
  },
  {
    id: 'data-converter',
    name: 'JSON ⇄ YAML ⇄ XML',
    description: 'Convert configuration and payloads between JSON, YAML and XML in one click.',
    category: 'Converters',
    path: '/converters/data',
    icon: 'ArrowLeftRight',
    keywords: ['json', 'yaml', 'xml', 'convert', 'transform', 'config'],
  },
  // Testers
  {
    id: 'regex',
    name: 'Regex Playground',
    description: 'Test regular expressions with live highlighting, capture groups and handy presets.',
    category: 'Testers',
    path: '/testers/regex',
    icon: 'Regex',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test', 'capture', 'groups'],
  },
  {
    id: 'http',
    name: 'HTTP Sandbox',
    description: 'Fire HTTP requests, inspect status / headers / body, and copy as a cURL command.',
    category: 'Testers',
    path: '/testers/http',
    icon: 'Globe',
    keywords: ['http', 'rest', 'api', 'request', 'curl', 'get', 'post', 'put', 'delete', 'postman'],
  },
]

export const TOOL_CATEGORIES = [
  'Formatters',
  'Viewers',
  'Encoders',
  'Crypto',
  'Generators',
  'Converters',
  'Testers',
] as const

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.id === id)
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category)
}
